org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.114

mod_id=thaumaturgesdelight
mod_name=Thaumaturge's Delight
mod_license=LGPL-3.0
mod_version=0.0.1
mod_group_id=com.blackmoss.thaumaturgesdelight

thaumaturge_version=26.1.2-NeoForge-BETA-0.2.1
## 26.1.2-1.3.3-fix5
farmers_delight_version=9006218
lithostitched_version=1.8.0-neoforge-26.1
jei_version=29.6.2.31
curios_version=15.0.0+26.1.2
jade_version=26.1.11+neoforge
